---
title: "Power BioTechNan info"
output: ioslides_presentation
widescreen: true

---

## BioTechNan – Program Interdyscyplinarnych Środowiskowych Studiów Doktoranckich KNOW z obszaru Biotechnologii i Nanotechnologii

Celem głównym projektu jest zwiększenie do marca 2023 r. jakości i efektywności kształcenia na studiach doktoranckich realizowanych z zakresu Biotechnologii i Nanotechnologii na:

- Politechnice Wrocławskiej, Uniwersytecie Wrocławskim, Uniwersytecie Przyrodniczym we Wrocławiu oraz Instytucie Immunologii i Terapii Doświadczalnej im. Ludwika Hirszfelda Polskiej Akademii Nauk

poprzez utworzenie i realizację nowych Środowiskowych Interdyscyplinarnych Studiów Doktoranckich w ramach partnerstwa KNOW, skierowanych do 30 doktorantów.

## BioTechNan – Program Interdyscyplinarnych Środowiskowych Studiów Doktoranckich KNOW z obszaru Biotechnologii i Nanotechnologii

Studia będą prowadzone w jednostkach posiadających prestiżowy status Krajowego Naukowego Ośrodka Wiodącego („KNOW”) w dziedzinach Nauk Biologicznych, Nauk Rolniczych i Nauk o Ziemi nadany przez Ministerstwo Nauki i Szkolnictwa Wyższego.

Grupą docelową jest 30 doktorantów, którzy odbędą pełny 4-letni cykl kształcenia na stacjonarnych środowiskowych studiach doktoranckich w zakresie bio- i nanotechnologii.

##  Realizacja programu studiów doktoranckich

- Kierownik Studiów Doktoranckich w każdej jednostce realizującej projekt przekazuje do Biura Projektu informacje o zaliczeniu semestru. 
- Zaliczenie następuje w oparciu o obowiązujące we właściwej jednostce przepisy oraz na podstawie wymaganych w danej jednostce dokumentów służących weryfikacji postępów w pracy badawczej Uczestnika projektu.
- Raz w roku akademickim, zostanie zorganizowane wspólne seminarium dla wszystkich uczestników projektu, na którym będą prezentowane postępy i osiągnięcia doktorantów, którzy osiągnęli najlepsze wyniki.


##  Stypendia dla uczestników Projektu

- Stypendia w wysokości 2 000,00 zł miesięcznie, po złożeniu przez doktoranta stosownego wniosku.
- Wsparcie stypendialne przyznawane jest na okres 6 mies., od października do marca roku następnego oraz od kwietnia do września, z uwzględnieniem weryfikacji postępów pracy badawczej doktoranta po każdym semestrze.
- Z doktorantem zostanie zawarta umowa stypendialna, na podstawie której otrzyma stypendium na 6-cio miesięczny okres odbywania
Interdyscyplinarnych Środowiskowych Studiów Doktoranckich. 
- Przedłużenie okresu pobierania stypendium na kolejne okresy wymaga każdorazowo aneksu do zawartej umowy stypendialnej. 
- Pani Viola przygotuje umowy później, jak się zapozna z projektem.

##  Finanse projektu (proste kalkulacje)

- Okres realizacji projektu: 1 kwietnia 2018 r. – 31 marca 2023 r.
- Całkowita wartość projektu: 3 948 852,75 zł
- Średnia na doktoranta: 131628,425 zł
- Średnia - stypendia = kwota na wyjazd: 35628,425 zł

##  Wydział Biotechnologii

- Zaplanowano staże 1-miesieczne dla 5 doktorantów.
- Doktorant uczestniczący w stażu otrzyma stypendium stażowe na poczet zakwaterowania i wyżywienia.
- Prócz stypendium doktorant otrzymuje także zwrot kosztów podróży.
- Wyjazdy na staże mają być realizowane corocznie w latach 2019-2022. W 2021 r. mają odbyć się 2 wyjazdy.
- 1 doktorant może wyjechać w danym roku?

##  Finanse Wydział Biotechnologii

- Łączna kwota na stypendia stażowe dla 5 doktorantów wynosi 38 430,00 zł
- Uśredniona kwotę 7686,00 zł na 1-miesięczny staż 1 doktoranta.
- Na finansowanie kosztów podróży jest łącznie 10 583,00 zł
- Uśredniona kwota ok. 2100 zł na wyjazd 1 doktoranta.
- Łącznie 9786,00 zł na wyjzad.

##  Finanse Wydział Biotechnologii dla 4 doktorantów (nieoficjalnie)

- Łączna kwota na stypendia stażowe wynosi 38 430,00 zł
- Uśredniona kwotę 9607,50 zł na 1-miesięczny staż 1 doktoranta.
- Na finansowanie kosztów podróży jest łącznie 10 583,00 zł
- Uśredniona kwota ok. 2645,75 zł na wyjazd 1 doktoranta.
- Łącznie 12253,25 zł na wyjzad.
- Stypendium 2500,00 zł (info od doktorantki prof. Łukaszewicza 2200)

## Oficjalna odpowiedz "Czy jeśli na naszym wydziale przyjęto mniej osób to czy budżet na wyjazdy na doktoranta się zwiększa?"

- Środki przewidziane na stypendia doktorantów podlegają zwrotowi, jeśli zrekrutowanych zostało mniej osób niż zostało założone we wniosku. 
- Ewentualne wykorzystanie części tych środków na zwiększenie budżetu na wyjazdy wymagałoby zgody Narodowego Centrum Badań i Rozwoju. 
- W dokumentacji konkursowej została określona maksymalna wysokość kosztów na uczestnika, która nie może być przekroczona. 
- Przy zmniejszeniu liczby uczestników, a jednoczesnym zwiększeniu budżetu na wyjazdy, automatycznie rośnie całkowity koszt na uczestnika.
- Niedozwolone jest, by przekroczył on wartość określoną w dokumentacji konkursowej – niespełnianie tego kryterium na etapie składania wniosku oznaczało odrzucenie projektu.

## Oficjalna odpowiedz "Czy podobnie jest ze stypendiami?"

- Wysokość stypendium została określona na tym samym poziomie dla wszystkich jednostek uczestniczących w projekcie, niezależnie od liczby doktorantów w danej jednostce. 
- Nie ma możliwości zwiększenia wysokości stypendium.

## Oficjalna odpowiedz "Czy staż może trwać dłużej, jeśli zostaną pieniądze w budżecie do wykorzystania?"

- W przypadku oszczędności w projekcie, można je wykorzystać na dodatkowy staż czy wydłużenie czasu trwania staży. 
- W zależności od charakteru zmian i wartości oszczędności, może być uprzednio konieczne zgłoszenie zmiany do NCBR.

## Oficjalna odpowiedz "Kiedy najwcześniej można składać wniosek o wyjazd i gdzie należy to zrobić?"

- Zgodnie z harmonogramem, pierwszy staż finansowany z projektu na Wydziale Biotechnologii jest przewidziany na 2019 r. 
- W II kwartale 2019 r. przewidziane jest wydatkowanie środków na stypendium stażowe i zwrot kosztów podróży uczestnika stażu. 
- Najwcześniej staż mógłby się odbyć na przełomie I i II kwartału 2019 r.

Podstawą wyjazdu na staż będzie umowa zawarta między jednostką a podmiotem przyjmującym na staż oraz umowa stażowa z uczestnikiem. Po powrocie uczestnik będzie zobowiązany do złożenia sprawozdania ze stażu. Są to minimalne wymagania, wspólne dla wszystkich partnerów, wynikające z wniosku. Natomiast wyjazdy będą organizowane zgodnie z wewnętrznymi procedurami obowiązującymi w danej jednostce. 
